name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, wait for review]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: dbeaver-version
    attributes:
      label: DBeaver version
      description: What version of DBeaver are you running?
      placeholder: ex. Community Edition 22.1.0
    validations:
      required: false
  - type: input
    id: os-kind
    attributes:
      label: Kind of operating system
      description: Could you please fill a OS and enhancment do you use?
      placeholder: ex. Ubuntu 20.4
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
  - type: markdown
    attributes: 
      label: log-files
        After creating a bug report, we will review it. We may need logs and in this article we talked about how to extract them [Wiki:Log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
    validations:
      required: false
      render: shell
