name: ✨ New Feature
description: Suggest an idea for DBeaver
labels: [feature request]
body:
  - type: textarea
    id: description
    attributes:
      label: Summary
      description: >
        Describe the new feature/improvement you would like briefly below.


        What's the problem this feature will solve?

        What are you trying to do, that you are unable to achieve
        with DBeaver as it currently stands?


        * Provide examples of use cases that this would enable
        and how it solves the problem you described.

        * How do you solve this now?

        * Have you tried to work around the problem using other options?
      placeholder: I am trying to do X with DBeaver and
                   I think that implementing a feature Y would be very helpful for me and 
                   other user of DBeaver because of Z.
    validations:
      required: true
